# Tạo các danh sách chứa câu hỏi theo từng chủ đề

# Câu hỏi về sản phẩm
questions_product = [
    "Hoa hồng đỏ có sẵn không?",
    "Cửa hàng có loại hoa nào nở lâu nhất?",
    "Hoa baby màu hồng có không?",
    "Loại hoa nào phù hợp để tặng sinh nhật?",
    "Có bán hoa cẩm chướng không?",
    "Hoa cẩm tú cầu giá bao nhiêu?",
    "Có bán cây xanh trang trí nhỏ không?",
    "Hoa lan hồ điệp có những màu nào?",
    "Hoa hồng vàng có nghĩa là gì?",
    "Hoa lily trắng có phải hoa tươi không?",
    "Hoa nào bền màu nhất trong vòng một tuần?",
    "Cửa hàng có hoa nhập khẩu không?",
    "Loại hoa nào hợp để tặng kỉ niệm ngày cưới?",
    "Có bán giỏ hoa để trưng phòng khách không?",
    "Có thể mua bó hoa mix nhiều loại không?",
    "Hoa baby có bán theo bó nhỏ không?",
    "Hoa sen đá có nhiều loại không?",
    "Hoa lan hồ điệp bảo quản như thế nào?",
    "Có hoa hồng đen không?",
    "Hoa cúc tươi có thể giữ bao lâu?",
    "Loại hoa nào hợp phong thủy cho người mệnh Kim?",
    "Có thể tư vấn hoa cho ngày lễ không?",
    "Có bán kèm bình hoa không?",
    "Hoa cẩm tú cầu trồng ở nhà được không?",
    "Có hoa nào thích hợp cho trẻ nhỏ không?",
    "Hoa baby có mấy màu?",
    "Cửa hàng có bán hoa trang trí nội thất không?",
    "Có bán hoa cưới không?",
    "Hoa nào phù hợp để tặng bạn gái?",
    "Cửa hàng có bán lẵng hoa không?",
    "Hoa nào có thể trưng trong phòng ngủ?",
    "Hoa lan hồ điệp có thể sống lâu không?",
    "Loại hoa nào giữ màu lâu nhất?",
    "Có bán hoa nhập từ Hà Lan không?",
    "Hoa nào hợp với mùa đông?",
    "Có bán hoa tươi sấy khô không?",
    "Hoa baby có thể cắm lâu không?",
    "Hoa hồng có mấy màu tại cửa hàng?",
    "Có bán hoa mix mùa không?",
    "Hoa hồng đỏ có bó sẵn không?",
    "Hoa lavender có bán không?",
    "Hoa nào hợp để làm quà tặng công ty?",
    "Hoa baby trắng có tươi lâu không?",
    "Có bán hoa phù hợp với từng cung hoàng đạo không?",
    "Có thể đặt hoa màu theo yêu cầu không?",
    "Làm sao để đặt hoa qua website?",
    "Cần bao nhiêu lâu để chuẩn bị đơn đặt hàng?",
    "Có thể đặt hoa giao trong ngày không?",
    "Giao hoa đến tỉnh khác được không?",
    "Đặt hoa giao tận nhà có tốn phí không?",
    "Đặt hoa sinh nhật cần đặt trước bao lâu?",
    "Có thể đặt hoa qua điện thoại không?",
    "Có nhận đặt hoa số lượng lớn không?",
    "Có thể chọn thời gian giao hoa cụ thể không?",
    "Đặt hoa cho dịp lễ cần đặt trước bao lâu?",
    "Làm sao để liên hệ với cửa hàng?",
    "Có thể yêu cầu hỗ trợ trực tuyến không?",
    "Chính sách bảo hành hoa như thế nào?",
    "Nếu hoa bị hỏng khi giao có được đổi không?",
    "Hỗ trợ khách hàng qua số hotline không?",
    "Cửa hàng có chính sách hoàn tiền không?",
    "Nếu không hài lòng với sản phẩm, có đổi được không?",
    "Có thể nhờ tư vấn chọn hoa được không?",
    "Nếu hoa đến không đúng loại đã đặt thì sao?",
    "Đổi trả sản phẩm có mất phí không?",
]

chitchatSample = [
    "Thời tiết hôm nay như thế nào?",
    "Ngoài trời nóng bao nhiêu?",
    "Ngày mai có mưa không?",
    "Nhiệt độ hiện tại là bao nhiêu?",
    "Bạn có thể cho tôi biết điều kiện thời tiết hiện tại không?",
    "Cuối tuần này có nắng không?",
    "Nhiệt độ hôm qua là bao nhiêu?",
    "Đêm nay trời sẽ lạnh đến mức nào?",
    "Ai là tổng thống đầu tiên của Hoa Kỳ?",
    "Chiến tranh thế giới thứ hai kết thúc vào năm nào?",
    "Bạn có thể kể cho tôi về lịch sử của internet không?",
    "Tháp Eiffel được xây dựng vào năm nào?",
    "Ai đã phát minh ra điện thoại?",
    "Tên của bạn là gì?",
    "Bạn có tên không?",
    "Tôi nên gọi bạn là gì?",
    "Ai đã tạo ra bạn?",
    "Bạn bao nhiêu tuổi?",
    "Bạn có thể kể cho tôi một sự thật thú vị không?",
    "Bạn có biết bất kỳ câu đố thú vị nào không?",
    "Màu sắc yêu thích của bạn là gì?",
    "Bộ phim yêu thích của bạn là gì?",
    "Bạn có sở thích nào không?",
    "Ý nghĩa của cuộc sống là gì?",
    "Bạn có thể kể cho tôi một câu chuyện cười không?",
    "Thủ đô của Pháp là gì?",
    "Dân số thế giới là bao nhiêu?",
    "Có bao nhiêu châu lục?",
    "Ai đã viết 'Giết con chim nhại'?",
    "Bạn có thể cho tôi một câu nói của Albert Einstein không?"
]